import Head from "next/head";
import ProductCard from "../componets/ProductCard";
import React from "react";
import Header from "../componets/Header";
import Footer from "../componets/Footer";
import useFetch, { CachePolicies } from "use-http";

export default function Home() {
  const { data } = useFetch(
    "/api/hello",
    { cachePolicy: CachePolicies.NO_CACHE },
    []
  );
  const products = data?.products;
  return (
    <>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
          rel="stylesheet"
        />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://unpkg.com/flowbite@1.4.1/dist/flowbite.js"></script>
      </Head>
      <Header />
      {products?.map((p, id) => {
        return (
          <>
            {
              <ProductCard
                key={id}
                title={p?.title}
                rating={p?.ratings}
                stars={p?.stars}
                link={p?.link}
                img={p?.img}
              />
            }
          </>
        );
      })}
      <Footer />
    </>
  );
}
